In [1]:
import numpy as np
import pandas as pd

In [2]:
sample_list = [1,2,3,4,5]
sample_list

[1, 2, 3, 4, 5]

In [3]:
sample_array = np.array([1,2,3,4,5])
sample_array

array([1, 2, 3, 4, 5])

In [4]:
# 더하기 빼기 해보기
sample_array + 2

array([3, 4, 5, 6, 7])

In [5]:

sample_array_2 = np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10]])
sample_array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
sample_array_2.shape


(2, 5)

In [7]:
np.arange(start=1, stop=6, step=1)

array([1, 2, 3, 4, 5])

In [8]:
np.arange(start=0.1, stop=0.8, step=0.2)

array([0.1, 0.3, 0.5, 0.7])

In [9]:
np.tile("A",5)

array(['A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [11]:
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [13]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
d1= np.array([1,2,3,4,5,])
d1

array([1, 2, 3, 4, 5])

In [20]:
d1[1:5]

array([2, 3, 4, 5])

In [21]:
df = pd.DataFrame({
    'col1':sample_array,
    'col2':sample_array*2,
    'col3':["A","B","C","C","E"]
    
})
df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    C
4     5    10    E